config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'haikus#index'
  resources :haikus, only: [:index, :create, :show] do
    collection do
      get 'season_search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/haiku.rb
class Haiku < ApplicationRecord
  belongs_to :user, optional: true # optional: true → null登録を許容する

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :season

  with_options presence: true do
    validates :kami
    validates :naka
    validates :shimo 
  end

  validates :season_id, numericality: { other_than: 0, message: "can't be blank" } 

  def self.season_search(season_id)
      Haiku.where(season_id: season_id)
  end
end

app/models/season.rb
class Season < ActiveHash::Base
  self.data = [
    { id: 0, name: '季節' },
    { id: 1, name: '春' },
    { id: 2, name: '夏' },
    { id: 3, name: '秋' },
    { id: 4, name: '冬' }
  ]

  include ActiveHash::Associations
  has_many :haikus

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  # 6文字以上の半角英数字の制限
  validates :password,length: { minimum: 6 }, format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]/ }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  class ApplicationController < ActionController::Base
    before_action :store_user_location!, if: :storable_location?
    before_action :authenticate_user!

  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end
end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController

  def index
    @haikus = Haiku.includes(:user)
    @haiku = Haiku.new
  end

  def create
    @haiku = Haiku.new(haiku_params)
    if @haiku.save
      redirect_to root_path
    else
      render :index
    end
  end

  def show
    @haiku = Haiku.where(user_id: current_user.id)
  end

  def season_search
    @haikus = Haiku.where(season_id: params[:season_id])
    render :index
  end

  private

  def haiku_params
    if current_user.nil?
      params.require(:haiku).permit(:kami, :shimo, :naka, :season_id)
    else
      params.require(:haiku).permit(:kami, :shimo, :naka, :season_id).merge(user_id: current_user.id)
    end
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
 end
 
 def resource
    @resource ||= User.new
 end
 
 def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
 end
end

app/helpers/haikus_helper.rb
module HaikusHelper
end

app/views/haikus/index.html.erb
<body>

<%# 読み込みアニメ %>
<div id="splash">
  <div id="splash-logo">みんなの細道</div>
</div>
<div class="splashbg"></div>
<%# /読み込みアニメ %>

<%# モーダル %>
<div class="signup-modal-wrapper" id="signup-open">
  <!-- 新規登録用のモーダル -->

  <div class="modal" id="signup-modal">

    <%# 『閉じる』ボタン %>
    <div class="close-modal ">
      <i class="far fa-times-circle fa-lg close-btn"></i>
    </div>

    <div id="signup-form">
      <h2>Emailで新規登録</h2>

      <%= form_for(resource, as: resource_name, url: registration_path(resource_name) ) do |f| %>
        <%= devise_error_messages! %>

        <div class="field">
          <%= f.label :name, "名前"  %>
          <%= f.label :notion, "※必須項目です",class: "regist_notion"  %><br />
          <%= f.text_field :name ,class:"validate[required]" %>
        </div>

        <div class="field">
          <%= f.label :email, "メールアドレス" %>
          <%= f.label :notion, "※必須項目です",class: "regist_notion"  %><br />
          <%= f.email_field :email , class: " validate[required, custom[email]]" %>
        </div>

        <div class="field">
          <%= f.label :password, "パスワード" %>
          <%= f.label :notion, "※必須項目です",class: "regist_notion"  %><br />
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> 文字以上の半角英数字)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "off" , class: " validate[required, minSize[6]]", id: "passwd"%>
        </div>

        <div class="field">
          <%= f.label :password_confirmation, "パスワード再入力" %>
          <%= f.label :notion, "※必須項目です",class: "regist_notion"  %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off" , class: "validate[required, equals[passwd]]"%>
        </div>

        <div class="submit-btn-wrapper">
          <div class="actions" id="submit-btn">
            <%= f.submit "新規登録" %>
          </div>
        </div>
        
      <% end %>
      </div>
    </div>
  </div>
</div>

<div class="login-modal-wrapper" id="login-open">
<!-- ログイン用のモーダル -->
  <div class="modal" id="login-modal">

    <%# 『閉じる』ボタン %>
    <div class="close-modal">
      <i class="far fa-times-circle fa-lg close-btn"></i>
    </div>

    <div id="login-form">
      <h2>Emailログイン</h2>


      <%=  form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="field">
          <%= f.label :email, "メールアドレス" %><br />
          <%= f.email_field :email, autofocus: true ,class:"custom[email]" %>
        </div>

        <div class="field">
          <%= f.label :password, "パスワード" %><br />
          <%= f.password_field :password, autocomplete: "off" ,class:"validate[required]"%>
        </div>

        <% if devise_mapping.rememberable? %>
          <div class="field">
            <%= f.label :remember_me %><br />
            <%= f.check_box :remember_me %>
          </div>
        <% end -%>

        <div class="submit-btn-wrapper">
          <div class="actions" id="submit-btn">
            <%= f.submit "ログイン" %>
          </div>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

<div id="container"><%# 画面遷移用 %>
  <%# 巻物部分 %>
  <div class="makimono">
  
    <%# タイトル巻物 %>
    <div class="title-makimono">
      <div class="title">
        みんなのほそ道
      </div>
    </div>

    <%# /タイトル巻物 %>
    <%# メイン(投稿一覧)画面 %>
    <div class="card_wrapper">
      <h2>とうこういちらん</h2>
      <div class="haiku-list slide-paused" ontouchstart="">
        <% if @haikus.length < 6%>
          <ul class="card">
            <%= render partial: 'shared/haiku', collection: @haikus %>
          </ul>
        <% else %>
          <ul class="card">
            <%= render partial: 'shared/haiku', collection: @haikus %>
          </ul>
          <ul class="card">
            <%= render partial: 'shared/haiku', collection: @haikus %>
          </ul>
        <% end %>
      </div>
    </div>

    <%# /メイン(投稿一覧)画面 %>
    <%# サイドバー %>
    <div class="side_bar">
      <div class="top_wrapper">
        <div>
          <%= link_to "春", season_search_haikus_path(season_id: 1) %>
          <%= link_to "夏", season_search_haikus_path(season_id: 2) %>  
          <%= link_to "秋", season_search_haikus_path(season_id: 3) %>  
          <%= link_to "冬", season_search_haikus_path(season_id: 4) %> 
          <%= link_to "全て", root_path %>  
        </div>
        <div class="user-content">
          <% if user_signed_in? %>
            <%= link_to current_user.name, haiku_path(current_user.id) %>
            <%= link_to "ろぐあうと", destroy_user_session_path, method: :delete %>
          <% else %>
            <div class="btn" id="login-show">ろぐいん</div>
            <div class="btn signup signup-show" >しんきとうろく</div>
          <% end %>
        </div>
      </div>

      <%= form_with model: @haiku, local: true do |f| %>
        <div class="center_wrapper">
          <div class="haiku-post">
            <span>ここで一句</span>
          </div>
          <div class="field">
            上の句
            <%= f.text_area :kami, class: "inputfield inputfield_kami" %>
          </div>
          <div class="field">
            中の句
            <%= f.text_area :naka, class: "inputfield inputfield_naka" %>
          </div>
          <div class="field">
            下の句
            <%= f.text_area :shimo, class: "inputfield inputfield_shimo" %>
          </div>
        </div>

        <div class="bottom_wrapper">
          <div class="field-season">
            <%= f.collection_select(:season_id, Season.all, :id, :name, {}, {class:"season-select"}) %>
          </div>
          <div class="field">
            <%= f.submit "投稿", class: "send_btn" %>
          </div>
        </div>
      <% end %>
    </div>
    <%# /サイドバー %>
  </div>
  <%# /巻物部分 %>
</div>





</body>

app/views/haikus/show.html.erb
<div class="makimono">

  <%# 名前表示 %>
  <div class="title-makimono">
    <div class="title">
      <%= current_user.name %>さん
    </div>
  </div>
  <%# /名前表示 %>

  <%# 自分の投稿作品一覧 %>
  <div class="haiku-list slide-paused" ontouchstart="">>
    <% @haiku.each do %>
      <ul class="card">
        <%= render partial: 'shared/haiku', collection: @haiku %>
      </ul>
    <% end %>
  </div>
  <%# /自分の投稿作品一覧 %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />

    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
 <%# <!-- jQuery-validate-engin-railsの読み込み -->
    <script type="text/javascript">
      jQuery(document).ready(function($){
          jQuery("#validate_id").validationEngine();
      });
    </script>


    <!-- jQuery-validate-engin-railsの読み込み ここまで--> %>

    <title>みんなの細道</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- FontAwesomeの読み込み -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css"> 
    <!-- FontAwesomeここまで -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    

  </head>

  <body>
    <header>
    </header>
    <%= yield %>
    <footer>
    </footer>
    <script src="../javascript/modal_scr.js"></script>
    <script src="../javascript/load_anime.js"></script>
    
  </body>
</html>

app/views/shared/_haiku.html.erb
<% if haiku.season_id == 1 %>
  <li class="list content-hover spring_card_background">
<% elsif haiku.season_id == 2 %>
  <li class="list content-hover summer_card_background">
<% elsif haiku.season_id == 3 %>
  <li class="list content-hover autumn_card_background">
<% else %>
  <li class="list content-hover winter_card_background">
<% end %>
  <%= haiku.id %>
  <div class="card_kami">
    <%= haiku.kami %>
  </div>
  <div class="card_naka">
    <%= haiku.naka %>
  </div>
  <div class="card_shimo">
    <%= haiku.shimo %>
  </div>
  <div class="card_name">
    <% if haiku.user_id.nil? %>
      読み人知らず
    <% else %>
      <%= haiku.user.name %>
    <% end %>
  </div>
  <div class="card_success">
    いいね
  </div>
  <%= hidden_field_tag :season_id, haiku.season_id, id: "season_id" %>
</li>